CREATE TABLE AppLog(
USER_ID VARCHAR(50)   NOT NULL,
DATED   varchar(50)   NOT NULL,
LOGGER  VARCHAR(50)   NOT NULL,
LEVEL   VARCHAR(50)   NOT NULL,
MESSAGE VARCHAR(1500) NOT NULL
)ENGINE=InnoDB CHARSET=utf8;